FROM ubuntu:18.04


ENV DEBIAN_FRONTEND=noninteractive \ 
    LANG=C.UTF-8

RUN apt-get update && apt-get install -y \
    openjdk-8-jdk \
    wget \
    git \
    vim \
    tzdata 

COPY ./cherry /opt/cherry

WORKDIR /opt/cherry

RUN ./gradlew --refresh-dependencies

