version: '2.3'

services:
  web-springboot:
    build: .
    # image: cherry_market:0.0.1
    # container_name: cherry_market
    environment:
      - TZ=Asia/Seoul
    
    ports:
      - 8088:8088
    
    volumes:
      - /mnt/hdd_0/data/cherry:/opt/images
    restart: always
    depends_on:
      - oracle_db
  oracle_db:
    image: jaspeen/oracle-xe-11g
    container_name: oracle_db
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /mnt/hdd_0/db/oracle/cherry_market:/u01/app/oracle
    ports:
      - 1606:1521
  
