version: '2.3'

services:
  web-springboot:
    build: .
    environment:
      - TZ=Asia/Seoul
    
    ports:
      - 8088:8088
    
    volumes:
      - /mnt/hdd_0/data/cherry:/opt/images
    restart: always

